### ISSUE TITLE
Setup failed for custom integration asterisk_call_status: Requirements for asterisk_call_status not found: ['Pillow==9.4.0'].

### ISSUE THREAD

**Issue by DaN66O** [bkbilly/asterisk_call_status#6]
Good afternoon !!
I have updated Home Assistant to version 2023.7.2

I get the following errors and not working integration in Home Assistant

```
Setup failed for custom integration asterisk_call_status: Requirements for asterisk_call_status not found: ['Pillow==9.4.0'].
Unable to install package Pillow==9.4.0: ERROR: Cannot install Pillow==9.4.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```
Home Assistant uses Pillow==9.5.0
  But you have in the requirements ["asterisk-ami==0.1.5", "Pillow==9.4.0"]

**Comment by bkbilly** [comment]
I am also using the Home Assistant 2023.7.2, but I don't have this issue, but this may be because I don't use an integration that uses the Pillow package.
You could try editing the file `manifest.json` on your config directory where asterisk_call_status has been downloaded.
Change the `Pillow==9.4.0` to `Pillow==9.5.0` or `Pillow>=9.4.0`.

Please let me know if this fixes the issue.

**Comment by DaN66O** [comment]
`Pillow==9.4.0` it is written in the requirements of your integration.
It turns out that you decided that it is necessary to have a version `Pillow==9.4.0`
I deleted the line 
`"requirements": ["asterisk-ami==0.1.5", "Pillow==9.4.0"],`
and everything worked.

**Comment by bkbilly** [comment]
I wouldn't recommend deleting this line because it's crucial for the installation of the libraries.
In future updates or any change to your installation, it might stop working.
I would recommend what I wrote above which will look like this:
`"requirements": ["asterisk-ami>=0.1.5", "Pillow>=9.4.0"],`

**Comment by DaN66O** [comment]
I left
`"requirements": ["asterisk-ami>=0.1.5", "Pillow>=9.4.0"],`
Everything works

**Comment by bkbilly** [comment]
I've pushed an update with this fix.
